### PR TITLE
Holding details for 2018 event

### PR DESCRIPTION
**Pull request by DeckOfPandas**

### CODE REVIEW

**Comment by blu3id** [comment]
Can we update URLs as well? The sign-up still links to 2017 and the sponsorship info links to the 2017 document. Either strip or update?

Apart from accidentally dragging in the commits from #12 the rest looks ok... though may make some minor OCD tweaks... the pages are mainly Kramdown so while you _can_ use HTML it is probably better if you don't (well for my OCD anyway :P)

**Comment by mattstibbs** [comment]
@DeckOfPandas do we want to leave the 2017 agenda on there?

**Comment by DeckOfPandas** [comment]
Yes for illustrative purposes? Am also on phone atm, but can remove if you prefer

**Comment by mattstibbs** [comment]
Let's get it live!

**Comment by DeckOfPandas** [comment]
Thanks babe :)

**Comment by DeckOfPandas** [comment]
(calling men "babe" is an homage to awfulness)

**Pull request merged**
