### PR TITLE
Global alert

### PR DESCRIPTION
**Pull request by blu3id**
So... I noticed the new "Code of Conduct" page want really legible/responsive on mobile devices or narrow browser widths.

My intention was to simply fix this and add a nice generic "UK Healtcamp" header... I may have got slightly carried away and:
- Created a new global "Alert bar" so you only need to edit one file to update the bar on all pages
- Created a new `generic.html` template. This is used for the "Code of Conduct" page and could be used for other generic text pages
- Fixed-up some bits of css to be more responsive on mobile and enable the easy addition and removal of the alert bar without messing all the padding
- Made some subtle changes to links and file names to settle my OCD
- Added some documentation to `README.md`

Anyhow sorry procrastinating from real work....

### CODE REVIEW

**Comment by mattstibbs** [comment]
Is this what they mean when they say "the universe will provide"? I seem to have deployed something mediocre and by magic it's turned into something good :)

**Comment by mattstibbs** [comment]
@blu3id Have pulled the branch and had a look on my machine - looks great. I did think about pulling the banner out so that it was generic but skillz lacking :)

**Comment by DeckOfPandas** [comment]
@blu3id thanks so much, this is such a valuable contribution.

**Review by mattstibbs — APPROVED** [review]

**Comment by DeckOfPandas** [comment]
Ha, timing @mattstibbs

**Comment by mattstibbs** [comment]
@blu3id are you ready for this to be merged? :)

**Comment by blu3id** [comment]
Yeah, only some other small OCD targets to hit but you have to stop at some point...

**Comment by mattstibbs** [comment]
Tell you what - just mention myself or @DeckOfPandas in a comment when you're ready :)

**Comment by blu3id** [comment]
@DeckOfPandas @mattstibbs that was be saying I'm ready. My OCD will have to wait until there are more substantial changes to be made :D

**Comment by mattstibbs** [comment]
Super work - thanks @blu3id :)

**Pull request merged**
